apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: influxdb
  namespace: influxdb
spec:
  rules:
  - host: influxdb.d1cd8200-0db1-4515-8d1d-66fff66e2508.k8s.civo.com
    http:
      paths:
      - backend:
          serviceName: influxdb
          servicePort: 8086
